### ISSUE TITLE
Bootstrap css överlapp

### ISSUE THREAD

**Issue by jroxendal** [spraakbanken/skblportalen#1]
Det verkar finnas ett stort överlapp mellan bootstrap.css (från cdn) och bootstrap.theme.css (från skbl.se), bland annat är hela normalize.css och alla glyphicons inkluderad i bägge filer. det går nog att bli av med 100 KB genom att fixa det.

**Comment by anne17** [comment]
Fixed in https://github.com/spraakbanken/skblportalen/pull/4
