### ISSUE TITLE
Gzip för att spara KB

### ISSUE THREAD

**Issue by jroxendal** [spraakbanken/skblportalen#2]
Särskilt en sånhär sida:
https://skbl.se/sv/artikel (400+ KB) hade tjänat på att gzippas innan den skickas till klienten. Det är busenkelt att göra i flask med `flask-compress`:
https://pypi.python.org/pypi/Flask-Compress

**Comment by anne17** [comment]
Fixed in https://github.com/spraakbanken/skblportalen/pull/4
